# BlogSearch index building tool for Jekyll

// Asciidoc references
// Documentation: https://asciidoctor.org/docs/user-manual/
// Quick reference: https://asciidoctor.org/docs/asciidoc-syntax-quick-reference/
// Asciidoc vs Markdown: https://asciidoctor.org/docs/user-manual/#comparison-by-example
// GitHub Flavored Asciidoc (GFA): https://gist.github.com/dcode/0cfbf2699a1fe9b46ff04c41721dda74

:project-version: 0.0.3
:rootdir: https://github.com/kbumsik/blogsearch

ifdef::env-github[]
// Emoji
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
// URL
:imagesdir: https://gist.githubusercontent.com/path/to/gist/revision/dir/with/all/images
endif::[]

CAUTION: This is a part of link:{rootdir}[BlogSearch project]. If you would like to know the overall concept, go to link:{rootdir}[the parent directory].

## 1. Building a search index file

### Installation

[source,ruby]
----
group :jekyll_plugins do
  gem 'jekyll-blogsearch'

  ...
  Other jekyll plugins
  ...
end
----

### Configuration

CAUTION: Go to link:{rootdir}#whats-in-the-index[the "What's in the index file" section of the main project]. For more details on how to configure fields.

._config.yml
[source,yml,options="nowrap",subs="verbatim,attributes"]
----
titie: your-blog-website
email: your-email@example.com

url: "https://your-website"
baseurl: "/blog"

...
Other jekyll config
...

blogsearch:
  output: your_website_index.db.wasm # Generated blogsearch database file.
  fields: # See: {rootdir}#whats-in-the-index
    title:
      enabled: true
      indexed: true
      hasContent: true
    body:
      enabled: true
      indexed: true
      hasContent: true
    url:
      base: https://your-website/blog # url field has a special 'base' option to set the baseurl.
      enabled: true
      indexed: false
      hasContent: true
    categories:
      enabled: true
      indexed: true
      hasContent: true
    tags:
      enabled: false
      indexed: false
      hasContent: false
----

## 2. Enabling the search engine in the webpage

You need to enable the search engine in the web page. Go to link:../blogsearch[blogsearch Engine].

Again, if you would like to understand the concept of BlogSearch, go to link:{rootdir}[the parent directory].
