name: Build and Test CI

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  build-parts:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: make -C ${{ github.workspace }} install-in-docker
    - run: make -C ${{ github.workspace }} blogsearch-in-docker
    - run: make -C ${{ github.workspace }} blogsearch-crawler-in-docker
    - run: make -C ${{ github.workspace }} crawler-reactjs-in-docker
    - run: make -C ${{ github.workspace }} crawler-kubernetes-in-docker
    - run: make -C ${{ github.workspace }} gatsby-reactjs-in-docker
    - run: make -C ${{ github.workspace }} jekyll-circleci-in-docker
    - run: make -C ${{ github.workspace }} demo-in-docker

  build-all:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: make -C ${{ github.workspace }} install-in-docker
    - run: make -C ${{ github.workspace }} all-in-docker -j4 --output-sync=target

  # test:
  #   runs-on: ubuntu-latest
  #   steps:
  #   - uses: actions/checkout@v2
  #   - run: make -C ${{ github.workspace }} install-in-docker
  #   - run: make -C ${{ github.workspace }} test-in-docker -j4 --output-sync=target
